// Distributed under the MIT License.
// See LICENSE.txt for details.

#pragma once

#include <cstddef>
#include <string>
#include <tuple>
#include <utility>
#include <vector>

#include "DataStructures/DataBox/DataBox.hpp"
#include "Evolution/Systems/Cce/Actions/SendPsi0ToEvolution.hpp"
#include "Evolution/Systems/Cce/NewmanPenrose.hpp"
#include "Evolution/Systems/Cce/PreSwshDerivatives.hpp"

#include "NumericalAlgorithms/Spectral/SwshFiltering.hpp"
#include "IO/Observer/WriteSimpleData.hpp"
#include "Parallel/GlobalCache.hpp"
#include "Parallel/Invoke.hpp"

#include "Utilities/Gsl.hpp"
#include "Utilities/MakeString.hpp"
#include "Utilities/System/ParallelInfo.hpp"
#include "Utilities/TMPL.hpp"

namespace Cce {
namespace Actions {
namespace detail {
struct ScriOutput1 {
  static std::string name() noexcept { return "InnerPsi0"; }
};
}
/*!
 * \ingroup ActionsGroup
 * \brief Calculates \f$\Psi_0\f$ and its radial derivative
 * \f$\partial_\underline{\lambda}\Psi_0\f$ on the inner boundary of
 * CCE domain.
 *
 * \details This action is to be called after `Tags::BondiJ` has been updated.
 * Note that `Tags::BondiJ` is in the asymptotically inertial frame, while the
 * returned \f$\Psi_0\f$ and its radial derivative are in the Cauchy frame.
 * \f$\underline \lambda\f$ is an affine parameter along the null
 * rays generated by \f$l\f$, see Eq. (19a) in Moxon et al, arXiv:2007.01339.
 */
struct CalculatePsi0 {
  using const_global_cache_tags = tmpl::list<Tags::LMax>;

  template <typename DbTags, typename... InboxTags, typename Metavariables,
            typename ArrayIndex, typename ActionList,
            typename ParallelComponent>
  static std::tuple<db::DataBox<DbTags>&&> apply(
      db::DataBox<DbTags>& box,
      const tuples::TaggedTuple<InboxTags...>& /*inboxes*/,
      const Parallel::GlobalCache<Metavariables>& /*cache*/,
      const ArrayIndex& /*array_index*/, const ActionList /*meta*/,
      const ParallelComponent* const /*meta*/) noexcept {
    const size_t l_max = db::get<Tags::LMax>(box);
    const double radius = db::get<InitializationTags::ExtractionRadius>(box);
    db::mutate_apply<Interpolate_BondiJ>(make_not_null(&box));
    db::mutate_apply<PreSwshDerivatives<Tags::Dy<Tags::BondiJCauchyView>>>(
        make_not_null(&box));
    db::mutate_apply<
        PreSwshDerivatives<Tags::Dy<Tags::Dy<Tags::BondiJCauchyView>>>>(
        make_not_null(&box));
    db::mutate_apply<VolumeWeyl<Tags::Psi0Match>>(make_not_null(&box));
    db::mutate<Tags::TetradCoeffTheta>(
        make_not_null(&box),
        [&radius](
            const gsl::not_null<Scalar<SpinWeighted<ComplexDataVector, 0>>*>
                theta_tetrad) noexcept {
          get(*theta_tetrad).data() *= radius;
        });
    db::mutate<Tags::TetradCoeffPhi>(
        make_not_null(&box),
        [&radius](
            const gsl::not_null<Scalar<SpinWeighted<ComplexDataVector, 2>>*>
                phi_tetrad) noexcept { get(*phi_tetrad).data() *= radius; });
    db::mutate_apply<PreSwshDerivatives<Tags::Dy<Tags::Psi0Match>>>(
        make_not_null(&box));
    db::mutate_apply<BoundaryWeyl>(make_not_null(&box));

    db::mutate<Tags::BoundaryValue<Tags::Psi0Match>>(
        make_not_null(&box),
        [
          &l_max
        ](const gsl::not_null<Scalar<SpinWeighted<ComplexDataVector, 2>>*>
              psi_0_bound) noexcept {
          Spectral::Swsh::filter_swsh_boundary_quantity(
              make_not_null(&get(*psi_0_bound)), l_max, l_max-3);
        });

    return {std::move(box)};
  }
};

template <typename CceComponent>
struct TransferPsi0 {
  template <typename DbTags, typename... InboxTags, typename Metavariables,
            typename ArrayIndex, typename ActionList,
            typename ParallelComponent>
  static auto apply(db::DataBox<DbTags>& box,
                    const tuples::TaggedTuple<InboxTags...>& /*inboxes*/,
                    Parallel::GlobalCache<Metavariables>& cache,
                    const ArrayIndex& /*array_index*/,
                    const ActionList /*meta*/,
                    const ParallelComponent* const /*meta*/) noexcept {
    Parallel::simple_action<Actions::SendPsi0<Metavariables, CceComponent>>(
        Parallel::get_parallel_component<CceComponent>(cache),
        db::get<::Tags::TimeStepId>(box));
    return std::forward_as_tuple(std::move(box));
  }
};

template <typename ObserverWriterComponent>
struct WritePsi0 {
  template <typename DbTags, typename... InboxTags, typename Metavariables,
            typename ArrayIndex, typename ActionList,
            typename ParallelComponent>
  static std::tuple<db::DataBox<DbTags>&&> apply(
      db::DataBox<DbTags>& box,
      const tuples::TaggedTuple<InboxTags...>& /*inboxes*/,
      Parallel::GlobalCache<Metavariables>& cache,
      const ArrayIndex& /*array_index*/, const ActionList /*meta*/,
      const ParallelComponent* const /*meta*/) noexcept {

     auto& my_proxy =
          Parallel::get_parallel_component<ParallelComponent>(cache);
     auto observer_proxy =
         Parallel::get_parallel_component<ObserverWriterComponent>(
             cache)[static_cast<size_t>(
             Parallel::my_node(*my_proxy.ckLocal()))];
     auto psi0_observe = db::get<Tags::BoundaryValue<Tags::Psi0Match>>(box);
     std::vector<std::string> file_legend(2);
     std::vector<double> data_to_write(2);
    //file_legend.reserve(2);
    //file_legend.push_back("time1");
    //file_legend.push_back("time2");
    file_legend[0]="time1";
    file_legend[1]="time2";
    data_to_write[0]=real(get(psi0_observe).data()[0]);
    data_to_write[1]=imag(get(psi0_observe).data()[0]);
     Parallel::threaded_action<observers::ThreadedActions::WriteSimpleData>(
         observer_proxy, file_legend, data_to_write,
        "/" + detail::ScriOutput1::name());
    return std::forward_as_tuple(std::move(box));
   }

};

}  // namespace Actions
}  // namespace Cce
